version: '3.7'

services:

  web:
    container_name: reactweb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    depends_on: 
      - webapi
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  webapi:
    image: testwebapi_webapi #webapi 如果需要build image則不需定義既有的image
    container_name: webapi
    # build: 
    #   context: .
    networks: 
      webapi_network:
        ipv4_address: 172.28.0.2
    expose: 
      - 5000
    ports: 
      - 5000:5000
    depends_on: 
      - db
    # network_mode: "host"

  db:
    image: mysql:5.7
    container_name: mysql
    networks: 
      webapi_network:
        ipv4_address: 172.28.0.3
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
    expose: 
      - 3306
    ports: 
      - 6306:3306
    volumes: 
      - ./mysqlDB:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    networks: 
      webapi_network:
        ipv4_address: 172.28.0.4

    depends_on: 
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

networks:
    webapi_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
                  gateway: 172.28.0.1      