version: '3.7'

services:

  web:
    container_name: reactweb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    depends_on: 
      - webapi
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  webapi:
    image: webapi
    expose: 
      - 5000
    ports: 
      - 5000:5000